/*
 * Copyright (C) 2018 Pineapple Soft
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package timestablesgui;
import timestablescore.*;

/**
 * @version 1.0.0
 * @author David Ward
 */
public class TimesTablesWindow extends javax.swing.JFrame {

    /**
     * Creates new form TimesTablesWindow
     */
    public TimesTablesWindow() {
        initComponents();
        doCalculate();
        setRandoms();
    }
    
    public void doCalculate()
    {
        int firstNumber = firstNumberList.getSelectedIndex() + 1;
        int secondNumber = secondNumberList.getSelectedIndex() + 1;
        String answer = String.valueOf(Multiplication.multiply(firstNumber, secondNumber));
                
        answerBox.setText(answer);
    }
    
    public void setRandoms()
    {
        firstRandom.setText(String.valueOf(Random.RANDOM_INT(1, 12)));
        secondRandom.setText(String.valueOf(Random.RANDOM_INT(1, 12)));
    }
    
    public void checkAnswer()
    {
        int firstGeneratedNumber = Integer.valueOf(firstRandom.getText());
        int secondGeneratedNumber = Integer.valueOf(secondRandom.getText());
        int answerSubmit = Integer.valueOf(answerSubmitted.getText());
        int correctAnswer = firstGeneratedNumber * secondGeneratedNumber;
        
        boolean correct = Multiplication.checkAnswer(firstGeneratedNumber, secondGeneratedNumber, answerSubmit);
        if(correct)
        {
            answerMessage.setText("Correct! " + firstGeneratedNumber + " x " + secondGeneratedNumber + " = " + answerSubmit);
        }
        else
        {
            answerMessage.setText("Sorry, the correct answer was:\n" + firstGeneratedNumber + " x " + secondGeneratedNumber + " = " + correctAnswer);            
        }
        
        answerSubmitted.setText("");
        setRandoms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firstNumberList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        secondNumberList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        answerBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        firstRandom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondRandom = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        answerSubmitted = new javax.swing.JTextField();
        checkAnswerButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        answerMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Times Tables");

        firstNumberList.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        firstNumberList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        firstNumberList.setRequestFocusEnabled(false);
        firstNumberList.setSelectedIndex(0);
        firstNumberList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                firstNumberListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(firstNumberList);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Times");

        secondNumberList.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        secondNumberList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        secondNumberList.setSelectedIndex(0);
        secondNumberList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                secondNumberListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(secondNumberList);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel2.setText("Equals");

        answerBox.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        answerBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        answerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerBox, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149))))))
        );

        jTabbedPane1.addTab("Times Tables", jPanel1);

        firstRandom.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        firstRandom.setText("12");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel4.setText("times");

        secondRandom.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        secondRandom.setText("12");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel6.setText("=");

        answerSubmitted.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        answerSubmitted.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answerSubmittedFocusGained(evt);
            }
        });
        answerSubmitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerSubmittedActionPerformed(evt);
            }
        });

        checkAnswerButton.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        checkAnswerButton.setText("Check Answer");
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        answerMessage.setColumns(20);
        answerMessage.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        answerMessage.setRows(5);
        answerMessage.setText("Type your answer in the box above then click the \nCheck Answer button.");
        jScrollPane3.setViewportView(answerMessage);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(firstRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(answerSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkAnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstRandom)
                    .addComponent(jLabel4)
                    .addComponent(secondRandom)
                    .addComponent(jLabel6)
                    .addComponent(answerSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Test Your Knowledge", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        setBounds(0, 0, 707, 466);
    }// </editor-fold>//GEN-END:initComponents

    private void answerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBoxActionPerformed

    private void firstNumberListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_firstNumberListValueChanged
        doCalculate();
    }//GEN-LAST:event_firstNumberListValueChanged

    private void secondNumberListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_secondNumberListValueChanged
        doCalculate();
    }//GEN-LAST:event_secondNumberListValueChanged

    private void answerSubmittedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answerSubmittedFocusGained
        answerMessage.setText("");
    }//GEN-LAST:event_answerSubmittedFocusGained

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
        checkAnswer();
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    private void answerSubmittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerSubmittedActionPerformed
        checkAnswer();
    }//GEN-LAST:event_answerSubmittedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimesTablesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimesTablesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimesTablesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimesTablesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimesTablesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerBox;
    private javax.swing.JTextArea answerMessage;
    private javax.swing.JTextField answerSubmitted;
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JList<String> firstNumberList;
    private javax.swing.JLabel firstRandom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> secondNumberList;
    private javax.swing.JLabel secondRandom;
    // End of variables declaration//GEN-END:variables
}
